### ISSUE TITLE
Some warnings when compiling in C99

### ISSUE THREAD

**Issue by merqurio** [alvaroabascar/cneuron#2]
I tried to run it, and I think it didn't work, It drops everytime at `Epoch 4: 0 / 10000 (0.00%)`

``` bash
gcc    -c -o neuron.o neuron.c
neuron.c:395:17: warning: implicit declaration of function 'write' is invalid in C99 [-Wimplicit-function-declaration]
                write(fp, &(net->weights[l][n1][n2]), sizeof(float));
                ^
neuron.c:414:17: warning: implicit declaration of function 'read' is invalid in C99 [-Wimplicit-function-declaration]
                read(fp, &(net->weights[l][n1][n2]), sizeof(float));
                ^
2 warnings generated.
gcc    -c -o matrix.o matrix.c
gcc     nums_test.c neuron.o matrix.o  -lm -o nums_test
nums_test.c:36:5: warning: implicit declaration of function 'lseek' is invalid in C99 [-Wimplicit-function-declaration]
    lseek(train_lab, 8, SEEK_SET);
    ^
nums_test.c:39:9: warning: implicit declaration of function 'read' is invalid in C99 [-Wimplicit-function-declaration]
        read(train_lab, &dum, 1);
        ^
nums_test.c:72:12: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
    static maxhits = 0;
    ~~~~~~ ^
3 warnings generated.
gcc     save_test.c neuron.o matrix.o  -lm -o save_test
save_test.c:12:5: warning: implicit declaration of function 'vprint_float' is invalid in C99 [-Wimplicit-function-declaration]
    vprint_float(1, output);
    ^
save_test.c:15:5: warning: implicit declaration of function 'srand' is invalid in C99 [-Wimplicit-function-declaration]
    srand(time(NULL));
    ^
save_test.c:15:11: warning: implicit declaration of function 'time' is invalid in C99 [-Wimplicit-function-declaration]
    srand(time(NULL));
          ^
3 warnings generated.
```

:smile:

**Comment by alvaroabascar** [comment]
I'm embarrassed by what a mess I had in this repo. I've cleaned it a bit, and now it should be working. Go to src/test/, do make and run ./nums_test. It should be working.

Also, the implementation is quite a shit. I'm reimplementing everything in the branch "reimplement". The algorithm to train the network (backpropagation) is not finished yet, though.

**Comment by alvaroabascar** [comment]
btw I cannot reproduce the warnings.

**Comment by merqurio** [comment]
Ahaha, dont worry! I was just testing, I was curious about it. 

Maybe the compiler is the reason for those warnings

``` bash
gabi@Book:[~]$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

What compiler do you use ?

**Comment by alvaroabascar** [comment]
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)
